Added x86 'sha256/sha512' detection.
nihui/ruapu pull request #126
Opened 2024-09-29 09:39 UTC by whyb

## Added x86 'sha256/sha512' detection.
x86 sha isa reference: [Intel_SHA_extensions Wikipedia](https://en.wikipedia.org/wiki/Intel_SHA_extensions)
![圖片](https://github.com/user-attachments/assets/e30c0e50-e7cf-4c01-bf3d-062ebc58d373)

So I rename x86 'sha' to 'sha1'.

## Test
godbolt test:
![圖片](https://github.com/user-attachments/assets/f0bfbdeb-9a25-4c35-9aa9-62d9ce7b01d4)

2024-10-12 03:04 UTC, nihui requested changes

2024-10-12 03:04 UTC, nihui commented on ruapu.h
> +RUAPU_INSTCODE(sha512, 0xc4, 0xe2, 0x7f, 0xcd, 0xd1) // vsha512msg2 ymm1, ymm2
尽量使用 xmm0 ymm0 zmm0

2024-10-12 03:04 UTC, nihui commented on README.md
> +* [@whyb](https://github.com/whyb) &emsp;_Detect more x86 AMX_, SHA_, AVX512_
中间的下划线没有用吧

2024-10-12 07:43 UTC, whyb commented on README.md
> +* [@whyb](https://github.com/whyb) &emsp;_Detect more x86 AMX_, SHA_, AVX512_
> 中间的下划线没有用吧

I have made the changes according to your request.

New:
* [@whyb](https://github.com/whyb) &emsp;_Detect more x86 AMX*, SHA*, AVX512*, SM*

2024-10-12 07:45 UTC, whyb commented on ruapu.h
> +RUAPU_INSTCODE(sha512, 0xc4, 0xe2, 0x7f, 0xcd, 0xd1) // vsha512msg2 ymm1, ymm2
I have made the changes according to your request.
```c++
RUAPU_INSTCODE(sha1, 0x0f, 0x38, 0xc9, 0xc0) // sha1msg1 xmm0,xmm0
RUAPU_INSTCODE(sha256, 0x0f, 0x38, 0xcc, 0xc0) // sha256msg1 xmm0, xmm0
RUAPU_INSTCODE(sha512, 0xc4, 0xe2, 0x7f, 0xcd, 0xc0) // vsha512msg2 ymm0, ymm0
```
![圖片](https://github.com/user-attachments/assets/4b064eda-671b-4a1d-b17c-90b4d78b6e3c)

2024-10-14 08:01 UTC, nihui commented
please fix the conflicts ...

2024-10-14 10:10 UTC, whyb commented
> please fix the conflicts ...

Fixed conflicts.

2024-10-14 11:41 UTC, nihui requested changes

2024-10-14 11:41 UTC, nihui commented on .github/workflows/ci.yml
> +        ./ruapu
There is no flyci now

2024-10-15 06:36 UTC, merged

2024-10-15 06:36 UTC, nihui commented
Thanks for your contribution !