Added x86 'sm3/sm4' detection
nihui/ruapu pull request #127
Opened 2024-09-29 10:08 UTC by whyb

## Added x86 'sm3/sm4' detection
godbolt ISA test:
![圖片](https://github.com/user-attachments/assets/c1c5b10b-77c2-4ec8-b86c-1096a1ecc040)

## x86 ISA Document
### SM3
![圖片](https://github.com/user-attachments/assets/57f88ae8-3192-4ff4-9a1f-9922a41bd131)
### SM4
![圖片](https://github.com/user-attachments/assets/20ae5f90-a730-4e73-8f9e-0409cb8c4def)

2024-10-12 03:04 UTC, nihui requested changes

2024-10-12 03:04 UTC, nihui commented on ruapu.h
> +RUAPU_INSTCODE(sm4, 0xc4, 0xe2, 0x6e, 0xda, 0xd9) // vsm4key4 ymm1,ymm2,ymm3
尽量使用 xmm0 ymm0 zmm0

2024-10-12 07:49 UTC, whyb commented on ruapu.h
> +RUAPU_INSTCODE(sm4, 0xc4, 0xe2, 0x6e, 0xda, 0xd9) // vsm4key4 ymm1,ymm2,ymm3
> 尽量使用 xmm0 ymm0 zmm0

I have made the changes according to your request.
```c++
RUAPU_INSTCODE(sm3, 0xc4, 0xe2, 0x78, 0xda, 0xc0) // vsm3msg1 xmm0,xmm0,xmm0
RUAPU_INSTCODE(sm4, 0xc4, 0xe2, 0x7e, 0xda, 0xc0) // vsm4key4 ymm0,ymm0,ymm0
```
![圖片](https://github.com/user-attachments/assets/771a94a0-22a8-48ce-8dfb-fef276093464)

2024-10-14 06:59 UTC, merged

2024-10-14 06:59 UTC, nihui commented
Thanks for your contribution !